In [1]:
import pandas as pd

In [5]:
matches = pd.read_excel("../data_raw/WorldCupMatches.xlsx", sheet_name="World_Cup_Matches")

In [6]:
worldcups = pd.read_excel("../data_raw/WorldCupMatches.xlsx", sheet_name="World_Cups")

### Dataset Structure

In [7]:
worldcups.shape

(22, 10)

In [8]:
worldcups.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            22 non-null     int64
 1   Country         22 non-null     str
 2   Winner          22 non-null     str
 3   Runners-Up      22 non-null     str
 4   Third           22 non-null     str
 5   Fourth          22 non-null     str
 6   GoalsScored     22 non-null     int64
 7   QualifiedTeams  22 non-null     int64
 8   MatchesPlayed   22 non-null     int64
 9   Attendance      22 non-null     object
dtypes: int64(4), object(1), str(5)
memory usage: 1.8+ KB

In [9]:
matches.shape

(980, 20)

In [10]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  979 non-null    float64
 1   Datetime              980 non-null    str
 2   Stage                 980 non-null    str
 3   Stadium               980 non-null    str
 4   City                  980 non-null    str
 5   Home Team Name        980 non-null    str
 6   Home Team Goals       980 non-null    int64
 7   Away Team Goals       980 non-null    int64
 8   Away Team Name        980 non-null    str
 9   Win conditions        861 non-null    str
 10  Attendance            978 non-null    float64
 11  Half-time Home Goals  980 non-null    int64
 12  Half-time Away Goals  980 non-null    int64
 13  Referee               980 non-null    str
 14  Assistant 1           980 non-null    str
 15  Assistant 2           980 non-null    str
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    980 non-null    str
 19  Away Team Initials    980 non-null    str
dtypes: float64(4), int64(4), str(12)
memory usage: 153.3 KB

### Missing Data

In [11]:
worldcups.isnull().sum()

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

In [12]:
matches.isnull().sum()

Year                      1
Datetime                  0
Stage                     0
Stadium                   0
City                      0
Home Team Name            0
Home Team Goals           0
Away Team Goals           0
Away Team Name            0
Win conditions          119
Attendance                2
Half-time Home Goals      0
Half-time Away Goals      0
Referee                   0
Assistant 1               0
Assistant 2               0
RoundID                 128
MatchID                 128
Home Team Initials        0
Away Team Initials        0
dtype: int64

### Summary Statistics

In [13]:
worldcups.describe()

              Year  GoalsScored  QualifiedTeams  MatchesPlayed
count    22.000000    22.000000       22.000000      22.000000
mean   1978.909091   123.636364       22.227273      43.818182
std      27.738419    34.841882        7.602830      17.632860
min    1930.000000    70.000000       13.000000      17.000000
25%    1959.000000    90.500000       16.000000      32.000000
50%    1980.000000   129.000000       20.000000      45.000000
75%    2001.000000   146.750000       32.000000      64.000000
max    2022.000000   172.000000       32.000000      64.000000

In [14]:
matches.describe()

,Year,Home Team Goals,Away Team Goals,Attendance,Half-time Home Goals,Half-time Away Goals,RoundID,MatchID
count,979.000000,980.000000,980.000000,978.000000,980.000000,980.000000,8.520000e+02,8.520000e+02
mean,1989.620020,1.770408,1.040816,45837.525562,0.698980,0.425510,1.066177e+07,6.134687e+07
std,24.018454,1.593315,1.075480,22672.571226,0.934089,0.679153,2.729613e+07,1.110572e+08
min,1930.000000,0.000000,0.000000,2000.000000,0.000000,0.000000,2.010000e+02,2.500000e+01
25%,1974.000000,1.000000,0.000000,31725.000000,0.000000,0.000000,2.620000e+02,1.188750e+03
50%,1994.000000,1.000000,1.000000,42866.500000,0.000000,0.000000,3.370000e+02,2.191000e+03
75%,2010.000000,3.000000,2.000000,61374.500000,1.000000,1.000000,2.497220e+05,4.395006e+07
max,2022.000000,10.000000,7.000000,173850.000000,6.000000,5.000000,9.741060e+07,3.001865e+08

### Categorical Variables

In [15]:
worldcups["Country"].nunique()

17

From 1930 through 2022 only 18 countries have hosted the World Cup where Japan and Kore shared the tournament in 2002.

In [16]:
worldcups["Winner"].value_counts()

Winner
Brazil        5
Italy         4
Germany FR    3
Argentina     3
Uruguay       2
France        2
England       1
Spain         1
Germany       1
Name: count, dtype: int64

Brazil won the most World Cups!

In [18]:
matches["City"].nunique()

168

In [25]:
matches["Home Team Name"].value_counts()

Home Team Name
Brazil                        89
Argentina                     61
Italy                         57
Germany FR                    43
England                       41
                              ..
rn">Bosnia and Herzegovina     1
Egypt                          1
Iceland                        1
Panama                         1
United States                  1
Name: count, Length: 83, dtype: int64

168 cities hosted a match

In [17]:
matches["Stage"].value_counts()

Stage
Round of 16                 88
Quarter-finals              74
Group B                     72
Group A                     72
Group 1                     62
Group C                     60
Group D                     60
Group F                     60
Group E                     60
Group 2                     59
Group 3                     56
Group 4                     55
Group H                     42
Group G                     42
Semi-finals                 40
Final                       22
Match for third place       15
Group 6                     12
First round                  9
Preliminary round            8
Group 5                      6
Play-off for third place     4
Third place                  2
Name: count, dtype: int64

Groups used to be divided by numbers instead of letters, and even referred to as Preliminary round.

In [19]:
matches["Year"].min()

np.float64(1930.0)

In [20]:
matches["Year"].max()

np.float64(2022.0)